(os/cd "scripts/Cards/")
(def card-path (os/cwd))
(defn strip-extension [file] (string "./" (string/replace ".janet"  "" file)))
(each file (os/dir card-path) (import* (strip-extension file)) (printf "loaded %s" file))
(import* "../cards")
(print "Loaded")
