(os/cd "scripts/Cards/")
(def card-path (os/cwd))
(import ./test)
(defn strip-extension [file] (string "./" (string/replace ".janet"  "" file)))
(var cards @[])
(each file (os/dir card-path) (import* (strip-extension file)) (array/push cards (strip-extension file)) (printf "loaded %s" file))
(print "Loaded")
